#############################################################################
#                 █████╗ ██████╗ ███████╗███╗   ██╗ █████╗                  #
#                ██╔══██╗██╔══██╗██╔════╝████╗  ██║██╔══██╗                 #
#                ███████║██████╔╝█████╗  ██╔██╗ ██║███████║                 #
#                ██╔══██║██╔══██╗██╔══╝  ██║╚██╗██║██╔══██║                 #
#                ██║  ██║██║  ██║███████╗██║ ╚████║██║  ██║                 #
#                ╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═══╝╚═╝  ╚═╝                 #
#############################################################################
arena:
  start-timer: 30
  respawn-delay: 5
  island-radius: 15
  min-y-axis: 5
  player-hit-tag-length: 6 #in second
  game-end-delay: 6

  points:
    bed-destroy: 5
    kill: 1
    final-kill: 3
    death: -1

  disable-hunger: true
  game-lobby-scoreboard: 'game-lobby'

# Respawning
respawn-items:
  inventory:
    - 'wooden_sword'
  helmet: 'json::armor.helmet'
  chestplate: 'json::armor.chestplate'
  leggings: 'json::armor.leggings'
  boots: 'json::armor.boots'

# Traps

traps:
  trap-trigger-meantime: 5 # in seconds
  trap-queue:
    enabled: true
    queue-limit: 3
    queued-trap-cost:
      - '1:DIAMOND'
      - '2:DIAMOND'
      - '4:DIAMOND'


# Language

lang:
  parse-type: 'modern' #modern/legacy
  server-language: 'en_US'

  legacy-settings:
    translation-char: '&'

  modern-settings:
    compulsory-closing-tags: false
    discord-type-formatting: true
    enabled-transformations:
      click-event: true
      hover-event: true
      color: true
      decoration: true
      font: true
      gradient: true
      insertion: true
      keybind: true
      pre: true
      rainbow: true
      reset: true
      translatable: true