#############################################################################
#                 █████╗ ██████╗ ███████╗███╗   ██╗ █████╗                  #
#                ██╔══██╗██╔══██╗██╔════╝████╗  ██║██╔══██╗                 #
#                ███████║██████╔╝█████╗  ██╔██╗ ██║███████║                 #
#                ██╔══██║██╔══██╗██╔══╝  ██║╚██╗██║██╔══██║                 #
#                ██║  ██║██║  ██║███████╗██║ ╚████║██║  ██║                 #
#                ╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═══╝╚═╝  ╚═╝                 #
#############################################################################
arena:
  start-timer: 30
  respawn-delay: 5
  island-radius: 15
  min-y-axis: 5
  player-hit-tag-length: 6 #in second
  game-end-delay: 6

  points:
    bed-destroy: 5
    kill: 1
    final-kill: 3
    death: -1

  disable-hunger: true
  disable-vanilla-achievement: true