# SQLite
# MySQL
# MongoDB

database: SQLite

mysql:
  host: 'hostname'
  port: 3306
  database-name: 'dbedwars'
  username: 'admin'
  password: '123'
  reconnect: true
  ssl: false

mongodb:
  host: 'hostname'
  port: 27017
  database-name: 'dbedwars'