# SQLite
# H2
# MySQL
# PostGreSQL
# MongoDB

database: SQLite

mysql:
  host: 'hostname'
  port: 3306
  database-name: 'dbedwars'
  username: 'admin'
  password: '123'
  params: '?useUnicode=true&characterEncoding=utf8'

mongodb:
  host: 'hostname'
  port: 27017
  database-name: 'dbedwars'

store-match-history:
  enabled: true
  prune-time: 7d