name: DBedwars
version: 1.0
main: org.zibble.dbedwars.DBedwars
softdepend:
  - AutoNicker
  - BetterNick
  - Citizens
  - CMI
  - EazyNick
  - FeatherBoard
  - NametagEdit
  - NickAPI
  - NickNamer
  - PlaceholderAPI
  - PremiumVanish
  - PvPLevels
  - QuickBoard
  - SkinsRestorer
  - SlimeWorldManager
  - SuperVanish
  - TAB
  - Vault
  - VIPHide
commands:
  bedwars:
    aliases:
      - bw
      - bedwar