-- Create table `PLAYER_STATS`
CREATE TABLE IF NOT EXISTS `PLAYER_STATS` (
    `UUID` VARCHAR(36) UNIQUE PRIMARY KEY NOT NULL,
    `NAME` VARCHAR(16) NOT NULL,
    `LEVEL` INT NOT NULL,
    `LEVEL_PROGRESS` DOUBLE NOT NULL,
    `COINS` DOUBLE NOT NULL,
    `WINSTREAK` SMALLINT NOT NULL,
    `POINTS` DOUBLE NOT NULL
);